import Head from 'next/head';

export default function Home() {
  return (
    <>
    <Head>
      <title>Create Next App with Typescript/TailwindCSS</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <div className="container mx-auto flex flex-col items-center justify-center">
      <h1>Content Goes here</h1>
    </div>
    </>
  );
}
