import Head from 'next/head';

export default function Home() {
  return (
    <Head>
      <title>Create Next App with Typescript/TailwindCSS</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />

      <button type="button" className="btn btn-primary">
        Send
      </button>
    </Head>
  );
}
